### PR TITLE
#3 add fix for body background-color

### PR DESCRIPTION
**Pull request by baomastr**
add inline css for body background-color to fix the Android Chrome bug

### CODE REVIEW

**Comment by pocketjoso** [comment]
Hi @baomastr. This library is not hardcoded to be used for the document body, but can be used for any element on the page, as such the fix you submitted is not quite right. I did notice though that the default settings (which are to style the whole page with a fixed div) does allow for the bug you submitted to show on android phones.

I think we can fix this issue by making a change to the default `style` prop, here:
https://github.com/snipsco/react-scrolling-color-background/blob/master/src/index.js#L94
replacing: `bottom: '0px'`
with: `height: '100%'`

Can you try this fix instead, and if it works, update your PR with that change instead?

**Comment by baomastr** [comment]
@pocketjoso I've changed hardcode to function, that returnes `rgbString` as argument so that i can change my body background-color in parent element.

**Comment by baomastr** [comment]
fix with replacing default prop causes the same bug, but in bottom of page on Android Chrome. 
I thought it could be useful to have ability of getting `rgbString` in parent element. Let me know if you don't think so. I will remove this changes from my PR.

**Comment by pocketjoso** [comment]
With your solution you no longer have a need for the `render` function, in which case it imo no longer makes sense to use a react component. If you just wanted a callback on scroll to do your own rendering, then I suggest creating a separate library that is just a generic function that does this for you. You could even write it as a [react hook](https://reactjs.org/docs/hooks-intro.html) ⚠️ disclaimer - hooks are experimental!

For having something merged into this library, what I'm looking for is a fix that doesn't challenge what this library tries to do: render a changing color background into an element.
And while `height: 100%` doesnt work, **`height: 100vh` does! 🎉** (you still need to remove `bottom: 0`)

The problem is that apparently in mobile android browser what we see on screen when the navbar disappears is temporarily _taller_ than the 100% height, but as it works using the `vh` unit, **this is the solution I propose**.

**Comment by baomastr** [comment]
yeah. you're right. just passing prop style with `height: 100vh` resolves the problem. Thank you for help.

**Pull request closed without merging**
